CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE balance_transactions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    type           VARCHAR(255)                            NOT NULL,
    amount         INTEGER                                 NOT NULL,
    recognition_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_balance_transactions PRIMARY KEY (id)
);

CREATE TABLE departments
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE qualities
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    code   VARCHAR(255)                            NOT NULL,
    active BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_qualities PRIMARY KEY (id)
);

CREATE TABLE recognitions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    giver_id   BIGINT                                  NOT NULL,
    quality_id BIGINT                                  NOT NULL,
    message    VARCHAR(1000)                           NOT NULL,
    points     INTEGER                                 NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_recognitions PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE user_balances
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    giveable_points INTEGER                                 NOT NULL,
    last_reset_date date                                    NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_balances PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    active        BOOLEAN                                 NOT NULL,
    department_id BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE qualities
    ADD CONSTRAINT uc_qualities_code UNIQUE (code);

ALTER TABLE user_balances
    ADD CONSTRAINT uc_user_balances_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE balance_transactions
    ADD CONSTRAINT FK_BALANCE_TRANSACTIONS_ON_RECOGNITION FOREIGN KEY (recognition_id) REFERENCES recognitions (id);

ALTER TABLE balance_transactions
    ADD CONSTRAINT FK_BALANCE_TRANSACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE recognitions
    ADD CONSTRAINT FK_RECOGNITIONS_ON_GIVER FOREIGN KEY (giver_id) REFERENCES users (id);

ALTER TABLE recognitions
    ADD CONSTRAINT FK_RECOGNITIONS_ON_QUALITY FOREIGN KEY (quality_id) REFERENCES users (id);

ALTER TABLE recognitions
    ADD CONSTRAINT FK_RECOGNITIONS_ON_QUALITY7lwu0M FOREIGN KEY (quality_id) REFERENCES qualities (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE user_balances
    ADD CONSTRAINT FK_USER_BALANCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);